//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher_NFS_WPF_New.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher_NFS_WPF_New.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Симулирует эффект капель дождя на экране..
        /// </summary>
        public static string AdditionalPostEffects {
            get {
                return ResourceManager.GetString("AdditionalPostEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сглаживание - это техника, используемая для устранения ступенчатых краев на объектах.&quot;,
        ///&quot;Фильтрация текстур управляет тем, как 2D изображение (текстура) отображается на 3D модели, увеличивая четкость поверхности на расстоянии.
        /// </summary>
        public static string AntiAliasing {
            get {
                return ResourceManager.GetString("AntiAliasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модификация Need for Speed: Most Wanted - Speed Champions создана командой, увлеченной мирами игр. Модификация создана автором канала «One NFS Modding». Разработка лаунчера осуществлена ​​автором канала «Кодерские работы». Если вам интересно следить за творчеством авторов или вы просто хотите связаться с нами, мы будем рады, если вы подпишетесь на наши каналы.                                        ↓↓↓Ссылки ниже↓↓↓.
        /// </summary>
        public static string authorAbout {
            get {
                return ResourceManager.GetString("authorAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О нас.
        /// </summary>
        public static string authorAboutTitle {
            get {
                return ResourceManager.GetString("authorAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используемые ресурсы.
        /// </summary>
        public static string authorRes {
            get {
                return ResourceManager.GetString("authorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорогие геймеры! Мы искренне благодарим вас за выбор нашей модификации. Мы разработали ее с целью улучшить ваш игровой опыт и сделать его более увлекательным.  Ваша активность и обратная связь важны для нас. Мы всегда готовы выслушать ваши идеи и предложения. Вместе мы делаем игру лучше. Если у вас есть вопросы или предложения, не стесняйтесь обращаться к нам.  Спасибо, что выбрали нашу модификацию. Ваше участие сделает ее еще лучше! С наилучшими пожеланиями, Команда Speed Champions.❤️.
        /// </summary>
        public static string authorThanks {
            get {
                return ResourceManager.GetString("authorThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Благодарность вам.
        /// </summary>
        public static string authorThanksTitle {
            get {
                return ResourceManager.GetString("authorThanksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть.
        /// </summary>
        public static string authorView {
            get {
                return ResourceManager.GetString("authorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляет уровнем детализации мира, отражаемого в отражениях транспортных средств..
        /// </summary>
        public static string CarGeometryDetail {
            get {
                return ResourceManager.GetString("CarGeometryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регулирует частоту обновления отражения транспортного средства..
        /// </summary>
        public static string CarReflectionDetail {
            get {
                return ResourceManager.GetString("CarReflectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяет количество деталей мира, отражаемых в отражениях дороги..
        /// </summary>
        public static string CarReflectionResolutionScale {
            get {
                return ResourceManager.GetString("CarReflectionResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляет четкостью отражения транспортного средства..
        /// </summary>
        public static string CarReflectionUpdateRate {
            get {
                return ResourceManager.GetString("CarReflectionUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы только что произвели изменения в языковых настройках, лаунчер перезапустится..
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы изменили язык.
        /// </summary>
        public static string changeLanguageTitle {
            get {
                return ResourceManager.GetString("changeLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверить наличие обновлений.
        /// </summary>
        public static string checkUpdate {
            get {
                return ResourceManager.GetString("checkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция определяет соотношение сторон, в котором будут отображаться видеоролики на экране. Если у вас возникли проблемы с обрезанием видеороликов, отрегулируйте эту опцию..
        /// </summary>
        public static string CutscenesAspectRatio {
            get {
                return ResourceManager.GetString("CutscenesAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задает качество и реализм отражений..
        /// </summary>
        public static string DynamicShadows {
            get {
                return ResourceManager.GetString("DynamicShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяет, включены ли динамические тени в реальном времени, соответствующие углу солнца. Включение частичных динамических теней распространяет этот эффект на подвижные объекты, такие как транспортные средства и объекты окружающего мира. Выбор любой опции, кроме &apos;Включено&apos;, будет использовать статические тени, созданные заранее..
        /// </summary>
        public static string DynamicShadowsResolution {
            get {
                return ResourceManager.GetString("DynamicShadowsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вводит незаметные кинематографические эффекты, такие как свечение, зерно пленки, виньетирование, хроматическая аберрация и коррекция уровней изображения..
        /// </summary>
        public static string GameControllerSupport {
            get {
                return ResourceManager.GetString("GameControllerSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если у вас есть фоточувствительность, эта опция заменит видеоролики версиями, не содержащими ярких вспышек. Кроме того, здесь нет авторских прав на музыку, поэтому ее можно использовать для потокового воспроизведения или загрузки на видеоплатформы, такие как YouTube..
        /// </summary>
        public static string GameDifficulty {
            get {
                return ResourceManager.GetString("GameDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляет четкостью изображения в зеркале заднего вида..
        /// </summary>
        public static string GeneralReflectionDetail {
            get {
                return ResourceManager.GetString("GeneralReflectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный вами путь был неправельным повторите попытку..
        /// </summary>
        public static string incorretPathMessage {
            get {
                return ResourceManager.GetString("incorretPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляет четкостью отражений дороги..
        /// </summary>
        public static string MirrorReflectionDetail {
            get {
                return ResourceManager.GetString("MirrorReflectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяет количество деталей мира, видимых в зеркале заднего вида..
        /// </summary>
        public static string MirrorReflectionResolutionScale {
            get {
                return ResourceManager.GetString("MirrorReflectionResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляет уровнем детализации теней..
        /// </summary>
        public static string RainEffect {
            get {
                return ResourceManager.GetString("RainEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает поддержку контроллера, который вы хотите использовать..
        /// </summary>
        public static string RearviewMirrorForAllCarCameraViews {
            get {
                return ResourceManager.GetString("RearviewMirrorForAllCarCameraViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используемые ресурсы.
        /// </summary>
        public static string resourcesListTitle {
            get {
                return ResourceManager.GetString("resourcesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлений не найдено.
        /// </summary>
        public static string resultUpdate {
            get {
                return ResourceManager.GetString("resultUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сколько деталей мира будет
        ///                                            отражается в отражении дороги..
        /// </summary>
        public static string RoadReflectionsDetail {
            get {
                return ResourceManager.GetString("RoadReflectionsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насколько резким будет отражение дороги..
        /// </summary>
        public static string RoadReflectionsResolutionScale {
            get {
                return ResourceManager.GetString("RoadReflectionsResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включает зеркало заднего вида для всех видов камер автомобиля. Если отключено, оно будет видно только в режимах камеры бампера и капота..
        /// </summary>
        public static string SafetyCheckCutscenes {
            get {
                return ResourceManager.GetString("SafetyCheckCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео.
        /// </summary>
        public static string settingGameVideo {
            get {
                return ResourceManager.GetString("settingGameVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Графика.
        /// </summary>
        public static string settingsGameGraphics {
            get {
                return ResourceManager.GetString("settingsGameGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другое.
        /// </summary>
        public static string settingsGameOther {
            get {
                return ResourceManager.GetString("settingsGameOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        public static string settingsLauncherDefault {
            get {
                return ResourceManager.GetString("settingsLauncherDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена языка.
        /// </summary>
        public static string settingsLauncherLanguage {
            get {
                return ResourceManager.GetString("settingsLauncherLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к игре.
        /// </summary>
        public static string settingsLauncherPath {
            get {
                return ResourceManager.GetString("settingsLauncherPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить изменения.
        /// </summary>
        public static string settingsLauncherSave {
            get {
                return ResourceManager.GetString("settingsLauncherSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стилизация лаунчера.
        /// </summary>
        public static string settingsLauncherStyle {
            get {
                return ResourceManager.GetString("settingsLauncherStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здесь вы можете изменить настройки лаунчера.
        /// </summary>
        public static string settingsLauncherTitle {
            get {
                return ResourceManager.GetString("settingsLauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об авторах.
        /// </summary>
        public static string sideAboutAuthors {
            get {
                return ResourceManager.GetString("sideAboutAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string sideExit {
            get {
                return ResourceManager.GetString("sideExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки игры.
        /// </summary>
        public static string sideGameSettings {
            get {
                return ResourceManager.GetString("sideGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки лаунчера.
        /// </summary>
        public static string sideLauncherSettings {
            get {
                return ResourceManager.GetString("sideLauncherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть.
        /// </summary>
        public static string sidePlay {
            get {
                return ResourceManager.GetString("sidePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновления.
        /// </summary>
        public static string sideUpdates {
            get {
                return ResourceManager.GetString("sideUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяет уровень детализации окружающей среды. Уменьшение качества убирает некоторые модели/пропы и снижает разрешение текстур..
        /// </summary>
        public static string TextureFiltering {
            get {
                return ResourceManager.GetString("TextureFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        public static string updateCancel {
            get {
                return ResourceManager.GetString("updateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string updateLoad {
            get {
                return ResourceManager.GetString("updateLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на | |.
        /// </summary>
        public static string updateStop {
            get {
                return ResourceManager.GetString("updateStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Безопасные зоны предотвращают появление пользовательского интерфейса в технически используемых, но невидимых для игрока областях, таких как край экрана..
        /// </summary>
        public static string UserInterfaceSafeZone {
            get {
                return ResourceManager.GetString("UserInterfaceSafeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на V-Sync синхронизирует частоту кадров игры с частотой обновления вашего монитора, чтобы устранить разрыв изображения..
        /// </summary>
        public static string VSync {
            get {
                return ResourceManager.GetString("VSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменится, когда ваша игра запущена в полноэкранном режиме или оконном режиме..
        /// </summary>
        public static string WindowedMode {
            get {
                return ResourceManager.GetString("WindowedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Определяет уровень детализации для транспортных средств. В некоторых случаях это может убрать детали, такие как интерьер или световые блики..
        /// </summary>
        public static string WorldLevelOfDetail {
            get {
                return ResourceManager.GetString("WorldLevelOfDetail", resourceCulture);
            }
        }
    }
}
